title: Sah_Raw here, first website since 2020 ;)
description: > # this means to ignore newlines until "baseurl:"
  Find out just who Sah_Raw is, exactly
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sah-raw.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sarah Wambold # add your name
author-img: Swambold.jpg # add your photo
about-author: I am a technical writer and funeral director. I specialize in making hard things easier to understand. # add description
social-github: "https://github.com/sah-raw" # add your Github handle
social-linkedin: "https://www.linkedin.com/in/sarahwambold/" # add your Linkedin handle
social-email: "mailto:sarahwambold@gmail.com" # add your Email address


# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
